import { useMemo, useState } from 'react'

type Ticker = 'NVDA' | 'TSLA' | 'AAPL' | 'GME' | 'AMD'
type Dir = 'Up' | 'Down' | 'Flat'
type Impact = 'Low' | 'Medium' | 'High'

type StockModel = {
  name: string; price: number; changePct: number; marketStatus: 'Open'|'Closed'|'Pre-market'; updatedAt: string
  kpis: { momentum: number; retailHype: number; volatilityPressure: number; sentimentDivergence: number }
  riskLevel: 'Low'|'Moderate'|'Elevated'|'High'
  hypeVsFundamentals: { hype: number; fundamentals: number }
  historicalData: Array<{ label: string; price: number }>
  reasons: string[]
  signals: Array<{ signal: string; value: string; direction: Dir; impact: Impact }>
}
const STOCK_DATA: Record<Ticker, StockModel> = {
 NVDA:{name:'NVIDIA Corp.',price:1214.55,changePct:2.84,marketStatus:'Open',updatedAt:'3:42 PM ET',riskLevel:'Elevated',kpis:{momentum:86,retailHype:82,volatilityPressure:71,sentimentDivergence:63},hypeVsFundamentals:{hype:84,fundamentals:72},historicalData:[{label:'Apr 10',price:1038},{label:'Apr 15',price:1075},{label:'Apr 20',price:1049},{label:'Apr 25',price:1120},{label:'Apr 30',price:1158},{label:'May 05',price:1117},{label:'May 10',price:1190},{label:'May 14',price:1215}],reasons:['Retail mention velocity is 2.3× the 30-day average while realized volatility remains elevated.','Price acceleration is outpacing EPS revision trends, signaling potential narrative overshoot.','Options call skew is widening, suggesting crowding and higher downside convexity risk.'],signals:[{signal:'Social velocity',value:'+132%',direction:'Up',impact:'High'},{signal:'Implied vol rank',value:'74',direction:'Up',impact:'Medium'},{signal:'Earnings revision breadth',value:'+0.6%',direction:'Flat',impact:'Low'},{signal:'Put/Call ratio (7d)',value:'0.68',direction:'Down',impact:'Medium'}]},
 TSLA:{name:'Tesla Inc.',price:207.13,changePct:-1.16,marketStatus:'Open',updatedAt:'3:42 PM ET',riskLevel:'High',kpis:{momentum:61,retailHype:89,volatilityPressure:84,sentimentDivergence:77},hypeVsFundamentals:{hype:91,fundamentals:58},historicalData:[{label:'Apr 10',price:182},{label:'Apr 15',price:191},{label:'Apr 20',price:186},{label:'Apr 25',price:198},{label:'Apr 30',price:213},{label:'May 05',price:221},{label:'May 10',price:214},{label:'May 14',price:207}],reasons:['Hype growth remains strong while price trend has started flattening into distribution patterns.','Volatility pressure is near quarterly highs, increasing whipsaw and drawdown probability.','Sentiment-to-fundamentals spread remains wide relative to historical baseline.'],signals:[{signal:'Social velocity',value:'+176%',direction:'Up',impact:'High'},{signal:'Implied vol rank',value:'81',direction:'Up',impact:'High'},{signal:'Delivery estimate revisions',value:'-1.2%',direction:'Down',impact:'Medium'},{signal:'Put/Call ratio (7d)',value:'0.61',direction:'Down',impact:'Medium'}]},
 AAPL:{name:'Apple Inc.',price:196.48,changePct:0.72,marketStatus:'Open',updatedAt:'3:42 PM ET',riskLevel:'Moderate',kpis:{momentum:72,retailHype:64,volatilityPressure:48,sentimentDivergence:38},hypeVsFundamentals:{hype:62,fundamentals:76},historicalData:[{label:'Apr 10',price:171},{label:'Apr 15',price:174},{label:'Apr 20',price:170},{label:'Apr 25',price:177},{label:'Apr 30',price:181},{label:'May 05',price:184},{label:'May 10',price:189},{label:'May 14',price:196}],reasons:['Fundamental support remains solid, reducing overshoot risk versus high-hype names.','Volatility metrics are contained despite elevated market beta.','Sentiment divergence sits near neutral band, limiting near-term fragility.'],signals:[{signal:'Social velocity',value:'+38%',direction:'Up',impact:'Low'},{signal:'Implied vol rank',value:'46',direction:'Flat',impact:'Low'},{signal:'Earnings revision breadth',value:'+2.1%',direction:'Up',impact:'Low'},{signal:'Put/Call ratio (7d)',value:'0.84',direction:'Flat',impact:'Low'}]},
 GME:{name:'GameStop Corp.',price:34.97,changePct:9.44,marketStatus:'Open',updatedAt:'3:42 PM ET',riskLevel:'High',kpis:{momentum:79,retailHype:96,volatilityPressure:93,sentimentDivergence:88},hypeVsFundamentals:{hype:97,fundamentals:35},historicalData:[{label:'Apr 10',price:18},{label:'Apr 15',price:20},{label:'Apr 20',price:19},{label:'Apr 25',price:24},{label:'Apr 30',price:27},{label:'May 05',price:30},{label:'May 10',price:44},{label:'May 14',price:35}],reasons:['Extreme retail crowding and social amplification create unstable liquidity pockets.','Price and implied volatility both remain dislocated from earnings-linked valuation anchors.','Narrative momentum is highly reflexive, increasing gap-risk on sentiment reversals.'],signals:[{signal:'Social velocity',value:'+420%',direction:'Up',impact:'High'},{signal:'Implied vol rank',value:'95',direction:'Up',impact:'High'},{signal:'Earnings revision breadth',value:'-0.8%',direction:'Down',impact:'Medium'},{signal:'Put/Call ratio (7d)',value:'0.52',direction:'Down',impact:'High'}]},
 AMD:{name:'Advanced Micro Devices',price:172.04,changePct:1.34,marketStatus:'Open',updatedAt:'3:42 PM ET',riskLevel:'Elevated',kpis:{momentum:81,retailHype:74,volatilityPressure:69,sentimentDivergence:57},hypeVsFundamentals:{hype:79,fundamentals:68},historicalData:[{label:'Apr 10',price:149},{label:'Apr 15',price:153},{label:'Apr 20',price:151},{label:'Apr 25',price:157},{label:'Apr 30',price:163},{label:'May 05',price:167},{label:'May 10',price:170},{label:'May 14',price:172}],reasons:['Momentum is strong, but sentiment has started leading realized price by a widening margin.','Volatility pressure remains above semiconductor peer median.','Positioning skew indicates incremental crowding risk into catalyst windows.'],signals:[{signal:'Social velocity',value:'+89%',direction:'Up',impact:'Medium'},{signal:'Implied vol rank',value:'68',direction:'Up',impact:'Medium'},{signal:'Earnings revision breadth',value:'+1.4%',direction:'Up',impact:'Low'},{signal:'Put/Call ratio (7d)',value:'0.73',direction:'Flat',impact:'Low'}]},
}
const watchlist: Ticker[] = ['NVDA','TSLA','AAPL','GME','AMD']
const riskColor={Low:'text-emerald-300',Moderate:'text-amber-300',Elevated:'text-orange-300',High:'text-rose-300'}
const directionStyles={Up:'text-emerald-300 bg-emerald-500/10 border-emerald-500/30',Down:'text-rose-300 bg-rose-500/10 border-rose-500/30',Flat:'text-slate-300 bg-slate-500/10 border-slate-500/30'}
const buildPath=(v:number[],w:number,h:number)=>{const min=Math.min(...v),max=Math.max(...v),r=Math.max(max-min,1);return v.map((n,i)=>`${i?'L':'M'} ${((i/(v.length-1))*w).toFixed(2)} ${(h-((n-min)/r)*h).toFixed(2)}`).join(' ')}

export default function App(){
  const [ticker,setTicker]=useState<Ticker>('NVDA')
  const [sidebarOpen,setSidebarOpen]=useState(false)
  const stock=STOCK_DATA[ticker]
  const prices=stock.historicalData.map(x=>x.price)
  const min=Math.min(...prices),max=Math.max(...prices),range=Math.max(max-min,1)
  const chartPath=useMemo(()=>buildPath(prices,100,34),[ticker])
  const gaugePercent=Math.round((stock.kpis.volatilityPressure+stock.kpis.sentimentDivergence)/2)
  return <div className="min-h-screen overflow-x-hidden bg-slate-950 text-slate-100">
    <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_20%_0%,rgba(34,211,238,0.12),transparent_35%),radial-gradient(circle_at_95%_5%,rgba(59,130,246,0.15),transparent_30%)]"/>
    <div className="relative mx-auto grid min-h-screen w-full max-w-[1600px] grid-cols-1 lg:grid-cols-[260px_1fr]">
      <button onClick={()=>setSidebarOpen(v=>!v)} className="fixed left-4 top-4 z-30 rounded-lg border border-slate-700 bg-slate-900/90 px-3 py-2 text-xs lg:hidden">Menu</button>
      <aside className={`fixed inset-y-0 left-0 z-20 w-72 transform border-r border-slate-800/80 bg-slate-900/85 p-5 backdrop-blur-xl transition lg:static lg:w-auto lg:translate-x-0 ${sidebarOpen?'translate-x-0':'-translate-x-full'}`}>
        <h1 className="text-base font-semibold tracking-wide text-cyan-300 sm:text-lg">Stock Hype Risk Analyzer</h1>
        <p className="mt-1 text-[10px] uppercase tracking-[0.2em] text-slate-400 sm:text-xs">Fintech Dashboard</p>
        <nav className="mt-6 space-y-2 text-sm text-slate-300">{['Overview','Signals','Sentiment','Risk Lab'].map(s=><button key={s} className="w-full rounded-lg px-3 py-2 text-left transition hover:bg-cyan-500/10">{s}</button>)}</nav>
        <p className="mb-3 mt-8 text-xs uppercase tracking-[0.15em] text-slate-400">Watchlist</p>
        <div className="space-y-2">{watchlist.map(symbol=><button key={symbol} onClick={()=>{setTicker(symbol);setSidebarOpen(false)}} className={`flex w-full items-center justify-between rounded-xl border px-3 py-2 text-sm transition ${ticker===symbol?'border-cyan-400/60 bg-cyan-500/10 text-cyan-200':'border-slate-800 bg-slate-900/70 hover:border-slate-600'}`}><span>{symbol}</span><span className="text-xs text-slate-400">{STOCK_DATA[symbol].price.toFixed(2)}</span></button>)}</div>
      </aside>
      {sidebarOpen && <button className="fixed inset-0 z-10 bg-black/40 lg:hidden" onClick={()=>setSidebarOpen(false)} aria-label="Close sidebar"/>}
      <main className="p-3 pt-14 sm:p-5 sm:pt-16 md:p-7 lg:p-8 lg:pt-8">
        <section className="mb-5 rounded-2xl border border-slate-800 bg-slate-900/65 p-3 sm:p-4 backdrop-blur-xl"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4 text-sm sm:text-base"><div><p className="text-xs uppercase tracking-[0.15em] text-slate-400">Selected Ticker</p><p className="mt-1 text-lg font-semibold sm:text-xl">{ticker}</p><p className="text-xs text-slate-400">{stock.name}</p></div><div><p className="text-xs uppercase tracking-[0.15em] text-slate-400">Current Price</p><p className="mt-1 text-lg font-semibold sm:text-xl">${stock.price.toFixed(2)}</p><p className={`${stock.changePct>=0?'text-emerald-300':'text-rose-300'} text-xs`}>{stock.changePct>=0?'+':''}{stock.changePct.toFixed(2)}%</p></div><div><p className="text-xs uppercase tracking-[0.15em] text-slate-400">Market Status</p><p className="mt-1 inline-flex rounded-full border border-emerald-500/30 bg-emerald-500/10 px-3 py-1 text-xs sm:text-sm text-emerald-300">{stock.marketStatus}</p></div><div><p className="text-xs uppercase tracking-[0.15em] text-slate-400">Last Updated</p><p className="mt-1 text-lg font-semibold sm:text-xl">{stock.updatedAt}</p></div></div></section>
        <section className="grid grid-cols-1 gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Momentum Score',stock.kpis.momentum],['Retail Hype Index',stock.kpis.retailHype],['Volatility Pressure',stock.kpis.volatilityPressure],['Sentiment Divergence',stock.kpis.sentimentDivergence]].map(([l,v])=><article key={l} className="rounded-2xl border border-slate-800 bg-slate-900/65 p-4 sm:p-5"><p className="text-xs uppercase tracking-[0.15em] text-slate-400">{l}</p><p className="mt-2 text-2xl font-semibold text-cyan-200 sm:text-3xl">{v as number}<span className="text-xs text-slate-400 sm:text-sm">/100</span></p></article>)}</section>
        <section className="mt-5 grid gap-5 xl:grid-cols-[2fr_1fr]"><article className="rounded-2xl border border-slate-800 bg-slate-900/65 p-4 sm:p-5"><h2 className="text-base font-semibold sm:text-lg">Historical Price Trend</h2><div className="mt-3 rounded-xl border border-slate-800 bg-slate-950/70 p-3 sm:p-4"><svg viewBox="0 0 100 40" className="h-52 w-full sm:h-64 md:h-72"><defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#22d3ee" stopOpacity="0.4"/><stop offset="100%" stopColor="#22d3ee" stopOpacity="0"/></linearGradient></defs><path d={`${chartPath} L 100 40 L 0 40 Z`} fill="url(#chartFill)"/><path d={chartPath} fill="none" stroke="#22d3ee" strokeWidth="1.4"/>{stock.historicalData.map((p,i)=><circle key={p.label} cx={(i/(stock.historicalData.length-1))*100} cy={37-((p.price-min)/range)*34} r="0.7" fill="#67e8f9"/>)}</svg><div className="mt-2 grid grid-cols-4 gap-1 text-[10px] text-slate-500 sm:grid-cols-8 sm:text-[11px]">{stock.historicalData.map(p=><span key={p.label}>{p.label}</span>)}</div></div></article>
        <article className="rounded-2xl border border-slate-800 bg-slate-900/65 p-4 sm:p-5"><h2 className="text-base font-semibold sm:text-lg">Risk Gauge</h2><div className="mt-4 flex justify-center"><div className="relative h-32 w-32 sm:h-40 sm:w-40"><div className="absolute inset-0 rounded-full border-8 border-slate-800"/><div className="absolute inset-0 rounded-full border-8 border-transparent border-r-cyan-300 border-t-cyan-400" style={{transform:`rotate(${(gaugePercent/100)*270-135}deg)`}}/><div className="absolute inset-5 sm:inset-6 rounded-full bg-slate-950/90"/><div className="absolute inset-0 flex flex-col items-center justify-center"><span className={`text-lg font-semibold sm:text-xl ${riskColor[stock.riskLevel]}`}>{stock.riskLevel}</span><span className="text-xs text-slate-400">{gaugePercent}/100</span></div></div></div></article></section>
        <section className="mt-5 grid gap-5 xl:grid-cols-2"><article className="rounded-2xl border border-slate-800 bg-slate-900/65 p-4 sm:p-5"><h2 className="text-base font-semibold sm:text-lg">Hype vs Fundamentals</h2><div className="mt-4 space-y-4">{[['Hype',stock.hypeVsFundamentals.hype,'bg-cyan-400'],['Fundamentals',stock.hypeVsFundamentals.fundamentals,'bg-indigo-400']].map(([l,v,c])=><div key={l}><div className="mb-1 flex justify-between text-sm"><span>{l}</span><span>{v}</span></div><div className="h-3 rounded-full bg-slate-800"><div className={`h-3 rounded-full ${c}`} style={{width:`${v}%`}}/></div></div>)}</div></article><article className="rounded-2xl border border-slate-800 bg-slate-900/65 p-4 sm:p-5"><h2 className="text-base font-semibold sm:text-lg">Why this risk level?</h2><ul className="mt-3 space-y-2 text-sm text-slate-300">{stock.reasons.map(r=><li key={r} className="rounded-lg border border-slate-800 bg-slate-950/60 px-3 py-2">• {r}</li>)}</ul></article></section>
        <section className="mt-5 rounded-2xl border border-slate-800 bg-slate-900/65 p-4 sm:p-5"><h2 className="text-base font-semibold sm:text-lg">Signal Breakdown</h2><div className="mt-3 overflow-x-auto"><table className="min-w-full text-left text-xs sm:text-sm"><thead className="text-[10px] uppercase tracking-[0.12em] text-slate-400 sm:text-xs"><tr className="border-b border-slate-800"><th className="px-2 py-2 sm:px-3 sm:py-3">Signal</th><th className="px-2 py-2 sm:px-3 sm:py-3">Value</th><th className="px-2 py-2 sm:px-3 sm:py-3">Direction</th><th className="px-2 py-2 sm:px-3 sm:py-3">Risk Impact</th></tr></thead><tbody>{stock.signals.map(row=><tr key={row.signal} className="border-b border-slate-900/70"><td className="px-2 py-2 sm:px-3 sm:py-3">{row.signal}</td><td className="px-2 py-2 sm:px-3 sm:py-3">{row.value}</td><td className="px-2 py-2 sm:px-3 sm:py-3"><span className={`rounded-full border px-2 py-1 text-[10px] sm:text-xs ${directionStyles[row.direction]}`}>{row.direction}</span></td><td className="px-2 py-2 sm:px-3 sm:py-3"><span className={row.impact==='High'?'text-rose-300':row.impact==='Medium'?'text-amber-300':'text-emerald-300'}>{row.impact}</span></td></tr>)}</tbody></table></div></section>
      </main>
    </div>
  </div>
}
